export const endpoints = {
    login: "user/login",
    user_profile: 'login/user-profile',
    joinBet: 'bets/join',
    bets: 'bets',
    leaderboard: 'bets/leaderboard',
    myBet: 'bets/users/',
    recommendedBets: 'bets/recommended',
    editProfile: 'login/user-profile',
    addDevice: 'login/devices/map',
    deviceActivity: 'login/data',
    productList: 'shop/products',
    coupons: 'shop/coupons',
    addCart: 'shop/cart/add',
    checkout: 'shop/checkout',
    getHealthData: 'profile/',
    recharge_wallet: "/payment/recharge_wallet",
    login_data:"login/data",
    profile_userActivity: 'profile/user_activity/',
    wallet: '/wallet/',
    healthData:'profile/1/health-data',
    booster:'/boosters',
    purchase_booster:'/boosters/purchase',
    generateAadharOtp:'kyc/aadhaar/generate-otp',
    submitAadharOtp:'/kyc/aadhaar/submit-otp',
    verifyPan:'/kyc/verify-pan',
    verifyBank:'/kyc/verify-bank',
    all_bets:'/bets/all_bets',
    withdraw_winnings:'wallet/withdraw_winnings',
    send_fcm:'login/send-fcm',
    appVersion:'login/app-version',
}
